version: '3.4'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432
    
    env_file:
      - secret.env
    
    volumes:
      - ./db-data/:/var/lib/postgresql/data/


