version: '3.4'

services:

  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432
    
    env_file:
      - secret.env
    
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  pruebaapi:
    image: api
    build:
      context: .
      dockerfile: src/PruebaBackAPI/Dockerfile
    ports:
      - 7300:7300
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:7300
